name: Latest project list workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-github:
    name: Update this repo's README with latest project from github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
        comment_tag_name: PROJECT-LIST
          feed_list: "https://github.com/mrankitgupta?tab=repositories"